### ISSUE TITLE
建議~

### ISSUE THREAD

**Issue by aappme03** [v3921358/MapleStory-JavaScript#1]
宗達大大你好~
不知道有沒有興趣做一個 隨機髮型跟臉行的js呢 ?
還有之前看到實況有一個 GM密語 那個該怎麼新增呢? 可以請教一下嗎 感恩~

**Comment by v3921358** [comment]
https://github.com/v3921358/MapleStory-JavaScript/blob/master/Npc/%E7%BE%8E%E5%AE%B9Npc.js
已更新髮型及臉型Npc

------

密語那個就在你要的地方直接增加就好了
